# User Test
#------------------------------------
APP              = test
# App sources
APP_SRCS         = dt-naive.c data.c main.c
# App includes
APP_INC	         = 
# Compiler flags
APP_CFLAGS       = -O3
# Linker flags
APP_LDFLAGS      =

# Custom linker
APP_LINK_SCRIPT  =

include $(RULES_DIR)/pmsis_rules.mk