# User Test
#------------------------------------
APP              = test
# App sources
APP_SRCS         = dt-rec-utils.c main.c data.c dt-rec.c
# App includes
APP_INC	         =
# Compiler flags
APP_CFLAGS       = -O3
# Linker flags
APP_LDFLAGS      = 

# Custom linker
APP_LINK_SCRIPT  = 

# Macro Defining Stack Size
# MAIN_STACK_SIZE = 8192

include $(RULES_DIR)/pmsis_rules.mk